import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const require = createRequire(new URL('../../src/workbench/package.json', import.meta.url));
const { chromium } = require('playwright');
const base = process.env.CMEV_E2E_URL || 'http://127.0.0.1:5173';
const email = process.env.CMEV_DEMO_EMAIL || 'surveyor@claim-cmev.demo';
const password = process.env.CMEV_DEMO_PASSWORD || 'Demo2026!';
const artifacts = fileURLToPath(new URL('../../artifacts/evaluation/ui-baseline/', import.meta.url));
await mkdir(artifacts, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
page.setDefaultTimeout(30000);
const errors = [];
page.on('pageerror', error => errors.push(error.message));
async function screenshot(name) { await page.screenshot({ path: `${artifacts}/${name}.png`, fullPage: true }); }
async function api(path) {
  const response = await page.request.get(`${base}/api/v1${path}`);
  assert.equal(response.ok(), true, `${path}: ${response.status()}`);
  return response.json();
}
try {
  assert.equal((await context.request.get(`${base}/api/v1/claims`)).status(), 401);
  await page.goto(base);
  await page.getByRole('heading', { name: /Every claim/ }).waitFor();
  await screenshot('public-desktop');
  await page.getByRole('link', { name: 'Surveyor sign in' }).click();
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill('deliberately-wrong');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('alert').waitFor();
  assert.match(await page.getByRole('alert').innerText(), /incorrect/i);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await screenshot('login-desktop');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('heading', { name: /Claim queue/ }).waitFor();
  const claims = await api('/claims');
  assert.ok(claims.items.length >= 4);
  await page.getByLabel('Search claims').fill('CLM-24019');
  assert.equal(await page.locator('.claim-table tbody tr').count(), 1);
  await page.getByLabel('Search claims').fill('no-such-claim-xyz');
  await page.getByRole('heading', { name: 'No matching claims' }).waitFor();
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await screenshot('queue-desktop');
  await page.reload();
  await page.getByRole('heading', { name: /Claim queue/ }).waitFor();
  await page.getByRole('link', { name: 'CLM-24019', exact: true }).click();
  await page.getByRole('heading', { name: /CLM-24019/ }).waitFor();
  await screenshot('review-desktop');
  await page.goto(`${base}/claims/new`);
  const reference = `E2E-${Date.now()}`;
  await page.getByLabel('Claim reference').fill(reference);
  await page.getByLabel('Vehicle make').fill('Demo');
  await page.getByLabel('Vehicle model').fill('Synthetic Sedan');
  await page.getByLabel('Year', { exact: true }).fill('2021');
  await page.getByLabel('Registration plate').fill('DEMO 001');
  await page.getByLabel('Date of loss').fill('2026-09-20');
  const image = await readFile(new URL('../../src/workbench/public/images/damaged-car.png', import.meta.url));
  // Generated decorative image used only as an explicitly synthetic upload fixture.
  await page.locator('input[type=file]').nth(0).setInputFiles({ name: 'synthetic-photo.png', mimeType: 'image/png', buffer: image });
  await page.locator('input[type=file]').nth(1).setInputFiles({ name: 'synthetic-estimate.png', mimeType: 'image/png', buffer: image });
  await page.getByRole('button', { name: 'Upload & start review' }).click();
  await page.getByRole('heading', { name: reference + '.', exact: true }).waitFor({ timeout: 120000 });
  let cid = new URL(page.url()).pathname.split('/')[2];
  await page.getByRole('heading', { name: 'Estimate line items', exact: true }).waitFor({ timeout: 120000 });
  const uploaded = await api('/claims/' + cid);
  const uploadedAssessment = await api('/claims/' + cid + '/assessments/' + uploaded.assessment_revision);
  assert.equal(uploadedAssessment.provenance.source_kind, 'fixture');
  assert.equal(uploadedAssessment.files.length, 2);
  await screenshot('uploaded-fixture-review');
  // Uploaded claims deliberately select varied fixture scenarios; exercise mark recovery on the named seed.
  cid = claims.items.find(c => c.reference === 'CLM-24019').claim_id;
  await page.goto(base + '/claims/' + cid + '/review');
  await page.getByRole('heading', { name: 'Estimate line items', exact: true }).waitFor();
  const created = await api(`/claims/${cid}`);
  const assessment = await api(`/claims/${cid}/assessments/${created.assessment_revision}`);
  assert.equal(assessment.provenance.source_kind, 'fixture');
  assert.equal(assessment.line_items[0].effective_amount, null);
  assert.equal(assessment.finalize_preconditions.can_finalize, false);
  await screenshot('uploaded-review');
  const acceptanceNote = 'Synthetic browser acceptance note ' + Date.now();
  await page.getByLabel('Add note', { exact: true }).fill(acceptanceNote);
  let intercepted = false;
  await page.route('**/assessments/*/notes', async route => {
    if (intercepted) return route.continue();
    intercepted = true;
    const committed = await route.fetch();
    assert.equal(committed.status(), 200);
    await route.abort('failed'); // committed server-side, acknowledgement lost
  });
  await page.getByRole('button', { name: 'Save note', exact: true }).click();
  await page.getByRole('button', { name: 'Retry saved request', exact: true }).waitFor();
  await page.reload();
  await page.getByRole('button', { name: 'Retry saved request', exact: true }).click();
  await page.locator('.review-history').getByText(acceptanceNote, { exact: true }).waitFor();
  await page.waitForFunction(() => !document.querySelector('[aria-label="Saved pending request"]'));
  const afterRetry = await api('/claims/' + cid + '/assessments/' + created.assessment_revision + '/review');
  assert.equal(afterRetry.actions.filter(a => a.type === 'note' && a.text === acceptanceNote).length, 1, 'Lost acknowledgement must not duplicate note');
  await page.unroute('**/assessments/*/notes');
  await page.getByLabel('Revised amount (SGD)').fill('980.25');
  await page.getByRole('button', { name: 'Confirm price change' }).click();
  await page.getByRole('button', { name: 'Finalize review', exact: true }).waitFor({ timeout: 120000 });
  await page.waitForFunction(() => [...document.querySelectorAll('button')].some(b => b.textContent.includes('Finalize review') && !b.disabled), { timeout: 120000 });
  const revised = await api(`/claims/${cid}`);
  assert.equal(revised.input_revision, created.input_revision + 1);
  assert.equal(revised.assessment_revision, created.assessment_revision + 1);
  const next = await api(`/claims/${cid}/assessments/${revised.assessment_revision}`);
  assert.equal(next.line_items[0].effective_amount, '980.25');
  assert.equal(next.finalize_preconditions.can_finalize, true);
  await page.reload();
  await page.locator('.review-history').getByText(acceptanceNote, { exact: true }).waitFor();
  const original = uploadedAssessment.files[0].url;
  assert.equal((await page.request.get(new URL(original, base).href)).status(), 200);
  await screenshot('confirmed-review');
  await page.getByRole('button', { name: 'Finalize review', exact: true }).click();
  await page.getByRole('link', { name: 'Print report' }).click();
  await page.getByRole('button', { name: 'Print to PDF' }).waitFor();
  await page.getByText('NOT RECORDED', { exact: true }).waitFor();
  assert.match(await page.locator('.report-paper').innerText(), /synthetic|fixture/i);
  await screenshot('frozen-report');
  await page.pdf({ path: `${artifacts}/frozen-report.pdf`, format: 'A4', printBackground: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${base}/claims`);
  await page.getByRole('heading', { name: /Claim queue/ }).waitFor();
  await screenshot('queue-mobile');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'Mobile document must not overflow horizontally');
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('heading', { name: 'Sign in to your workspace' }).waitFor();
  assert.equal((await page.request.get(`${base}/api/v1/claims`)).status(), 401);
  await page.goto(base);
  await page.getByRole('heading', { name: /Every claim/ }).waitFor();
  await screenshot('public-mobile');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ result: 'passed', claim: reference, screenshots: artifacts }, null, 2));
} finally { await browser.close(); }
